version: '3.7'
services:
  frontend:
    build:
      context: .
    tty: true
    ports:
      - "3000:3000"
    # volumes:
    #   - ./:/app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    # command: sh -c "npm i && npm run dev"
volumes:
  node_modules: